name: Merge

on:
  push:
    branches: [ main ]

jobs:
  run:
    name: Report coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-22.04 ]
        php-versions: ['8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, xdebug

      - name: PHP Version
        run: php -v

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer validate
          composer install --prefer-dist --no-progress --no-suggest

      - name: Test
        run: vendor/bin/phpunit

      - name: Report Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer check
          composer global require php-coveralls/php-coveralls
          export CODECOVERAGE=1 && vendor/bin/phpunit --coverage-clover=clover.xml
          php-coveralls --coverage_clover=clover.xml -v
  integration_test:
    name: Integration Test (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Docker Build
        run: docker build -t cakepreloader:test tests/ --no-cache --build-arg BRANCH=dev-${{ steps.branch-name.outputs.current_branch }}
      - name: Docker Run
        run: docker run -d cakepreloader:test
      - name: Test Container
        run: |
          if docker ps | grep "cakepreloader:test"; then
            echo "container is running"
          else
            echo "container is not running"
            exit 1
          fi